const biodata = [
  {
    img: '/edhozell.png',
    title: 'Edhozell',
    desc: `Edho Zell adalah seorang YouTuber yang terkenal dengan konten gaming dan komedi. Dia memiliki bisnis yang berfokus pada merchandise gaming dan barang-barang terkait kontennya.`,
    instagram: `https://instagram.com/edhozell`,
    youtube: `https://youtube.com/@edhozell`,
    facebook: `https://web.facebook.com/edho.zell`,
  },
  {
    img: '/attahalilintar.jpg',
    title: 'Atta Halilintar',
    desc: 'Atta Halilintar adalah seorang YouTuber yang terkenal dengan konten vlog, musik, dan tantangan. Dia juga memiliki berbagai bisnis, termasuk produk fashion, restoran, dan berbagai investasi di berbagai sektor.',
    instagram: 'https://www.instagram.com/attahalilintar',
    youtube: `https://www.youtube.com/@AttaHalilintar`,
    facebook: 'https://web.facebook.com/AttaHalilintar',
  },
  {
    img: '/radityadika.jpg',
    title: 'Raditya Dika',
    desc: 'Raditya Dika adalah seorang komedian, penulis, dan sutradara yang terkenal dengan vlog dan konten komedi di YouTube. Dia juga adalah penulis buku-buku terkenal dan memiliki bisnis penerbitan.',
    instagram: 'https://www.instagram.com/raditya_dika',
    youtube: 'https://www.youtube.com/@radityadika',
    facebook: 'https://web.facebook.com/radityadikapages',
  },
  {
    img: '/riaricis.jpg',
    title: 'Ria Ricis',
    desc: 'Ria Ricis adalah seorang YouTuber terkenal dengan konten hiburan, musik, dan tantangan. Dia memiliki bisnis pakaian sendiri yang dikenal sebagai "RR by Ria Ricis."',
    instagram: 'https://www.instagram.com/riaricis1795',
    youtube: 'https://www.youtube.com/@RicisOfficial1795',
    facebook: 'https://web.facebook.com/riaricisfansoficial',
  },
  {
    img: '/AurelieHermansyah.jpg',
    title: 'Aurelie Hermansyah',
    desc: 'Aurelie Hermansyah adalah seorang YouTuber dan penyanyi Indonesia yang terkenal dengan konten musiknya. Dia memiliki bisnis kosmetik dan perhiasan sendiri yang disebut "Aurelie Beauty.',
    instagram: 'https://www.instagram.com/aurelie.hermansyah',
    youtube: 'https://www.youtube.com/@AureliehermansyahOfficial',
    facebook: 'https://web.facebook.com/p/Aurelie-hermansyah-100044841243624',
  },
  {
    img: '/Gofar Hilman.jpg',
    title: 'Gofar Hilman',
    desc: 'Gofar Hilman adalah seorang YouTuber yang dikenal dengan kontennya tentang perjalanan, petualangan, dan kuliner. Dia juga memiliki bisnis makanan dan minuman, termasuk restoran sendiri.',
    instagram: 'https://www.instagram.com/pergijauh',
    youtube: 'https://www.youtube.com/@GofarHilman',
    facebook: 'https://web.facebook.com/gofarhilmansekut',
  },
  {
    img: '/Dian Sastro.jpg',
    title: 'Dian Sastro',
    desc: 'Dian Sastro adalah seorang aktris terkenal yang memiliki saluran YouTube pribadi. Dia menggunakan platform tersebut untuk berbagi wawasan tentang perempuan, keluarga, dan kesehatan.',
    instagram: 'https://www.instagram.com/therealdisastr',
    youtube: 'https://www.youtube.com/@VINDES',
    facebook: 'https://web.facebook.com/DianSastrowardoyo',
  },
  {
    img: '/jessnolimit.jpg',
    title: 'Jess No Limit (Jesslyn Limanu)',
    desc: 'Jess No Limit adalah seorang YouTuber gaming yang terkenal dengan konten permainan Mobile Legends. Dia memiliki bisnis merchandise yang terkait dengan kontennya.',
    instagram: 'https://www.instagram.com/jessnolimit',
    youtube: 'https://www.youtube.com/@JessNoLimit',
    facebook: 'https://web.facebook.com/jessnolimitasli',
  },
  {
    img: '/Thariq Halilintar.jpg',
    title: 'Thariq Halilintar',
    desc: 'Thariq Halilintar adalah anggota dari keluarga Halilintar yang terkenal di YouTube. Dia memiliki bisnis yang berfokus pada pendidikan, seperti kursus online dan platform belajar.',
    instagram: 'https://www.instagram.com/thariqhalilintar',
    youtube: 'https://www.youtube.com/@ThariqHalilintar',
    facebook: 'https://web.facebook.com/thariq.halilintar',
  },
];

export default biodata;
