import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import HeaderTop from '@/components/HeaderTop';
import HeaderMain from '@/components/HeaderMain';
import Navbar from '@/components/Navbar';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'DeskShoes',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        {/* <MobNavbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
