const productsData = [
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 5,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 3,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 3,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 5,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 3,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 3,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
  {
    img: '/jacket-1.jpg',
    title: 'NAMO BARANG',
    desc: 'DESKRIPSI',
    rating: 4,
    price: '5000',
  },
];

export default productsData;