const productsData = [
  {
    img: '/Sepatu Sneaker Velophasis Luxe Sport II.jpg',
    title: 'Sepatu Sneaker Velophasis Luxe Sport II',
    desc: 'Alas kaki',
    rating: 4,
    price: '2599000',
  },
  {
    img: '/Sepatu Kets RS-X 3D.jpg',
    title: 'Sepatu Kets RS-X 3D',
    desc: 'Alas kaki',
    rating: 5,
    price: '1424250',
  },
  {
    img: '/Sepatu Slipstream PUMA x THE SMURFS.jpg',
    title: 'Sepatu Slipstream PUMA x THE SMURFS',
    desc: 'Alas kaki',
    rating: 3,
    price: '2199000',
  },
  {
    img: '/Sepatu Sneaker PUMA x 8ENJAMIN Slipstream.jpg',
    title: 'Sepatu Sneaker PUMA x 8ENJAMIN Slipstream',
    desc: 'Alas kaki',
    rating: 4,
    price: '1499250',
  },
  {
    img: '/Sepatu Sneaker PUMA x RIPNDIP Slipstream.jpg',
    title: 'Sepatu Sneaker PUMA x RIPNDIP Slipstream',
    desc: 'Alas kaki',
    rating: 3,
    price: '2399000',
  },
  {
    img: '/Sepatu Sneaker RS-X Efekt Turbo.jpg',
    title: 'Sepatu Sneaker RS-X Efekt Turbo',
    desc: 'Alas kaki',
    rating: 4,
    price: '1499250',
  },
  {
    img: '/Sepatu Sneaker RS-X Elevated Hike.jpg',
    title: 'Sepatu Sneaker RS-X Elevated Hike',
    desc: 'Alas kaki',
    rating: 4,
    price: '1424250',
  },
  {
    img: '/Sepatu Sneaker RS-X Games.jpg',
    title: 'Sepatu Sneaker RS-X Games',
    desc: 'Alas kaki',
    rating: 4,
    price: '1899000',
  },
  {
    img: '/Sepatu Sneaker RS-X Geek.jpg',
    title: 'Sepatu Sneaker RS-X Geek',
    desc: 'Alas kaki',
    rating: 4,
    price: '1424250',
  },
  {
    img: '/Sepatu Sneaker RS-X Underground Drift.jpg',
    title: 'Sepatu Sneaker RS-X Underground Drift',
    desc: 'Alas kaki',
    rating: 5,
    price: '1999000',
  },
  {
    img: '/Sepatu Sneaker Slipstream Xtreme.jpg',
    title: 'Sepatu Sneaker Slipstream Xtreme',
    desc: 'Alas kaki',
    rating: 3,
    price: '2179000',
  },
  {
    img: '/Sepatu Trainer RS-X Reinvention.jpg',
    title: 'Sepatu Trainer RS-X Reinvention',
    desc: 'Alas kaki',
    rating: 4,
    price: '1899000',
  },
  {
    img: '/Sepatu Kets Pria Basket Classic 75Y.jpg',
    title: 'Sepatu Kets Pria Basket Classic 75Y',
    desc: 'Alas kaki',
    rating: 3,
    price: '1349250',
  },
  {
    img: '/Sepatu Sneaker PUMA x THE SMURFS RS-X.jpg',
    title: 'Sepatu Sneaker PUMA x THE SMURFS RS-X',
    desc: 'Alas kaki',
    rating: 4,
    price: '2099000',
  },
  {
    img: '/Sepatu Sneaker Teveris NITRO Vortex.jpg',
    title: 'Sepatu Sneaker Teveris NITRO Vortex',
    desc: 'Alas kaki',
    rating: 4,
    price: '1899000',
  },
  {
    img: '/Sepatu Sneaker Teveris Nitro.jpg',
    title: 'Sepatu Sneaker Teveris Nitro',
    desc: 'Alas kaki',
    rating: 4,
    price: '1349250',
  },
];

export default productsData;
